---
- name: Simple Web Application Deployment
  hosts: webservers
  become: yes

  tasks:
    - name: Install Apache HTTPD
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start and enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Clean existing web root
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Deploy simple application page
      copy:
        src: "webapp/index.html"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Deploy WAR file for download/backup
      copy:
        src: "webapp/myapp-1.0-SNAPSHOT.war"
        dest: /var/www/html/myapp.war
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Wait for Apache to be ready
      wait_for:
        port: 80
        delay: 5
        state: started
        timeout: 30

    - name: Test the deployment
      uri:
        url: "http://localhost/"
        method: GET
        status_code: 200
        timeout: 10

    - name: Show deployment info
      debug:
        msg: |
          🎉 Deployment Successful!
          
          Your application is now deployed at:
          🌐 http://{{ ansible_host }}/
          
          WAR file is available at:
          📦 http://{{ ansible_host }}/myapp.war
          
          To check status:
          🔍 systemctl status apache2
          📊 tail -f /var/log/apache2/access.log
