- hosts: webservers
  become: yes
  tasks:
    - name: Stop Tomcat
      systemd:
        name: tomcat
        state: stopped

    - name: Copy WAR to Tomcat webapps
      copy:
        src: target/myapp-1.0.0.war
        dest: /opt/tomcat/webapps/myapp.war
        mode: '0644'

    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started
