---
- name: Deploy Application using Apache HTTPD
  hosts: webservers
  become: yes
  vars:
    app_name: myapp
    web_root: /var/www/html

  tasks:
    - name: Update apt cache and install Apache HTTPD
      apt:
        update_cache: yes
        name:
          - apache2
        state: present

    - name: Ensure Apache is started and enabled
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: "{{ web_root }}/{{ app_name }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy web application files
      copy:
        src: "webapp/"
        dest: "{{ web_root }}/{{ app_name }}"
        owner: www-data
        group: www-data
        mode: '0644'
        directory_mode: '0755'

    - name: Create Apache virtual host configuration
      copy:
        dest: /etc/apache2/sites-available/{{ app_name }}.conf
        content: |
          <VirtualHost *:80>
              ServerName {{ ansible_host }}
              DocumentRoot {{ web_root }}/{{ app_name }}
              
              <Directory {{ web_root }}/{{ app_name }}>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
              
              ErrorLog ${APACHE_LOG_DIR}/{{ app_name }}_error.log
              CustomLog ${APACHE_LOG_DIR}/{{ app_name }}_access.log combined
          </VirtualHost>
        owner: root
        group: root
        mode: '0644'

    - name: Enable the new virtual host
      command: a2ensite {{ app_name }}.conf
      notify: restart apache

    - name: Disable default virtual host
      command: a2dissite 000-default.conf
      notify: restart apache

    - name: Enable required Apache modules
      command: "a2enmod {{ item }}"
      with_items:
        - rewrite
      notify: restart apache

    - name: Reload Apache configuration
      systemd:
        name: apache2
        state: reloaded

    - name: Wait for Apache to be ready
      wait_for:
        port: 80
        delay: 5
        state: started
        timeout: 60

    - name: Check application status
      uri:
        url: "http://localhost/{{ app_name }}/"
        method: GET
        status_code: 200
        timeout: 30
      register: app_status
      until: app_status.status == 200
      retries: 5
      delay: 10

    - name: Show deployment results
      debug:
        msg: |
          ==================== DEPLOYMENT SUMMARY ====================
          ✅ Application deployed successfully!
          
          Application URL: http://{{ ansible_host }}/{{ app_name }}/
          Web Root: {{ web_root }}/{{ app_name }}
          Apache Status: Running on port 80
          
          Files deployed:
          - index.html (test page)
          - myapp-1.0-SNAPSHOT.war (your application)
          
          Troubleshooting:
          - Check Apache logs: tail -f /var/log/apache2/{{ app_name }}_error.log
          - Check Apache status: systemctl status apache2
          - Test manually: curl http://localhost/{{ app_name }}/
          
          ============================================================

  handlers:
    - name: restart apache
      systemd:
        name: apache2
        state: restarted
