#- hosts: webservers
  #become: yes
  #tasks:
    #- name: Stop Tomcat
      #systemd:
        #name: tomcat
        #state: stopped

    #- name: Copy WAR to Tomcat webapps
      #copy:
        #src: target/myapp-1.0.0.war
        #dest: /opt/tomcat/webapps/myapp.war
        #mode: '0644'

    #- name: Start Tomcat
      #systemd:
        #name: tomcat
        #state: started 


---
- hosts: webservers
  become: yes
  vars:
    tomcat_version: "10.1.27"  # Change to the version you want
    tomcat_install_dir: "/opt/tomcat"
    tomcat_service_user: "ubuntu"
    tomcat_port: 8081         # Change to your desired port
    war_source: "target/myapp-1.0.0.war"
    war_dest: "{{ tomcat_install_dir }}/webapps/myapp.war"

  tasks:

    - name: Update apt and install dependencies
      apt:
        name: 
          - openjdk-17-jdk
          - wget
        state: present
        update_cache: yes

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /opt/
        remote_src: yes

    - name: Rename Tomcat directory
      command: mv /opt/apache-tomcat-{{ tomcat_version }} {{ tomcat_install_dir }}
      args:
        creates: "{{ tomcat_install_dir }}"

    - name: Make scripts executable
      file:
        path: "{{ tomcat_install_dir }}/bin/{{ item }}"
        mode: '0755'
      loop:
        - startup.sh
        - shutdown.sh

    - name: Configure Tomcat port
      lineinfile:
        path: "{{ tomcat_install_dir }}/conf/server.xml"
        regexp: '(<Connector port=").*?(")'
        line: '\1{{ tomcat_port }}\2'
        backrefs: yes

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking
          User={{ tomcat_service_user }}
          Group={{ tomcat_service_user }}
          Environment=JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          Environment=CATALINA_PID={{ tomcat_install_dir }}/temp/tomcat.pid
          Environment=CATALINA_HOME={{ tomcat_install_dir }}
          Environment=CATALINA_BASE={{ tomcat_install_dir }}
          ExecStart={{ tomcat_install_dir }}/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start Tomcat
      systemd:
        name: tomcat
        state: started
        enabled: yes

    - name: Stop Tomcat before deploying WAR
      systemd:
        name: tomcat
        state: stopped

    - name: Copy WAR to Tomcat webapps
      copy:
        src: "{{ war_source }}"
        dest: "{{ war_dest }}"
        mode: '0644'

    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started

