#- hosts: webservers
  #become: yes
  #tasks:
    #- name: Stop Tomcat
      #systemd:
        #name: tomcat
        #state: stopped

    #- name: Copy WAR to Tomcat webapps
      #copy:
        #src: target/myapp-1.0.0.war
        #dest: /opt/tomcat/webapps/myapp.war
        #mode: '0644'

    #- name: Start Tomcat
      #systemd:
        #name: tomcat
        #state: started 


---
- hosts: webservers
  become: yes
  vars:
    java_package: openjdk-17-jdk
    tomcat_version: 10.1.26
    tomcat_install_dir: /opt/tomcat
    tomcat_user: ubuntu
    tomcat_group: ubuntu
    tomcat_port: 8085
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

  tasks:
    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name: "{{ java_package }}"
        state: present

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /opt/
        remote_src: yes
      notify:
        - Set permissions

    - name: Rename Tomcat folder
      command: mv /opt/apache-tomcat-{{ tomcat_version }} {{ tomcat_install_dir }}
      args:
        removes: "{{ tomcat_install_dir }}"
      notify:
        - Set permissions

    - name: Set executable permissions for scripts
      file:
        path: "{{ tomcat_install_dir }}/bin/"
        recurse: yes
        mode: "0755"

    - name: Update Tomcat port
      lineinfile:
        path: "{{ tomcat_install_dir }}/conf/server.xml"
        regexp: 'port="8080"'
        line: 'port="{{ tomcat_port }}"'
        backrefs: yes

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking
          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          Environment=JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          Environment=CATALINA_PID={{ tomcat_install_dir }}/temp/tomcat.pid
          Environment=CATALINA_HOME={{ tomcat_install_dir }}
          Environment=CATALINA_BASE={{ tomcat_install_dir }}
          ExecStart={{ tomcat_install_dir }}/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: started

  handlers:
    - name: Set permissions
      file:
        path: "{{ tomcat_install_dir }}"
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: "0755"

