---
- name: Deploy Application to Tomcat
  hosts: webservers
  become: yes
  vars:
    tomcat_home: /opt/tomcat
    app_name: myapp

  tasks:
    - name: Check if Tomcat is installed
      stat:
        path: "{{ tomcat_home }}"
      register: tomcat_exists

    - name: Fail if Tomcat is not installed
      fail:
        msg: |
          Tomcat is not installed at {{ tomcat_home }}. 
          Please install Tomcat manually first with:
          sudo apt update
          sudo apt install openjdk-17-jdk wget -y
          wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.30/bin/apache-tomcat-10.1.30.tar.gz
          tar -xzf apache-tomcat-10.1.30.tar.gz -C /opt/
          ln -s /opt/apache-tomcat-10.1.30 /opt/tomcat
      when: not tomcat_exists.stat.exists

    - name: Check Tomcat service status
      systemd:
        name: tomcat
      register: tomcat_service
      ignore_errors: yes

    - name: Stop Tomcat service if running
      systemd:
        name: tomcat
        state: stopped
      when: tomcat_service.status is defined and tomcat_service.status.ActiveState == 'active'
      ignore_errors: yes

    - name: Clean existing deployment
      file:
        path: "{{ tomcat_home }}/webapps/{{ app_name }}.war"
        state: absent
      ignore_errors: yes

    - name: Clean existing exploded deployment
      file:
        path: "{{ tomcat_home }}/webapps/{{ app_name }}"
        state: absent
      ignore_errors: yes

    - name: Create temporary directory for WAR file transfer
      tempfile:
        state: directory
        suffix: "_war_transfer"
      register: temp_dir

    - name: Copy WAR file from Jenkins workspace to temporary directory
      copy:
        src: "myapp.war"
        dest: "{{ temp_dir.path }}/{{ app_name }}.war"
        mode: '0644'

    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ temp_dir.path }}/{{ app_name }}.war"
        dest: "{{ tomcat_home }}/webapps/{{ app_name }}.war"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        remote_src: yes

    - name: Set proper permissions on webapps directory
      file:
        path: "{{ tomcat_home }}/webapps"
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started

    - name: Wait for Tomcat to start
      wait_for:
        port: 8081
        delay: 10
        state: started
        timeout: 120

    - name: Wait for application to deploy
      pause:
        seconds: 30

    - name: Check application status
      uri:
        url: "http://localhost:8081/{{ app_name }}"
        method: GET
        status_code: 200, 404, 503
        timeout: 30
      register: app_status
      until: app_status.status != 503
      retries: 10
      delay: 10
      ignore_errors: yes

    - name: Show deployment results
      debug:
        msg: |
          Deployment Summary:
          - Tomcat URL: http://{{ ansible_host }}:8081
          - Application URL: http://{{ ansible_host }}:8081/{{ app_name }}
          - Application Status: {{ app_status.status }}

          {% if app_status.status == 200 %}
          ✅ Application deployed successfully and is responding
          {% elif app_status.status == 404 %}
          ⚠️  Application deployed but context path might be different
          Try: http://{{ ansible_host }}:8081/
          {% else %}
          🔧 Application might still be starting up
          {% endif %}

          To check Tomcat logs: journalctl -u tomcat -f
          To check application: curl http://localhost:8081/{{ app_name }}
